### ISSUE TITLE
タイタニック問題を解く

### ISSUE THREAD

**Issue by akihirookuda95** [akihiro-coder/Fresh-Vegetable-Price-Forecasts#2]

**Comment by sagamixaki** [comment]
# 学んだこと
- 特徴量エンジニアリング　基本
- アルゴリズムの選定
  - アルゴリズムの理論理解は後に行う
- 交差検証とハイパーパラメータのチューニングの実装

**Comment by sagamixaki** [comment]
# やること
- ロジスティック回帰で説明変数の正規化を行う　→　身長：0~1など
